### ISSUE TITLE
大佬你好，BEST_checkpoint下载下来不能解压（解压错误）能否重新发一份呢

### ISSUE THREAD

**Issue by chengdalei** [foamliu/Sentiment-Analysis#5]
大佬你好，BEST_checkpoint下载下来不能解压（解压错误）能否重新发一份呢

**Comment by foamliu** [comment]
You can load it directly, extraction is not needed.

**Comment by chengdalei** [comment]
> You can load it directly, extraction is not needed.

OK,thank you very much.
